image: hhy5861/java-ci:1.0.1

stages:
  - build

snapshot:
  stage: build
  script:
    - mvn clean deploy -Dmaven.test.skip=true
  tags:
    - develop
  only:
    - Alpha

releases:
  stage: build
  script:
    - mvn clean deploy -Dmaven.test.skip=true
  tags:
    - beta
  only:
    - tags
    
    
    
    